# YAML for launching the orderer
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peer0.org1.example.com
  labels:
    app: peer0.org1.example.com
spec:
  serviceName: peer0.org1.example.com
  replicas: 1
  selector:
    matchLabels:
      app: peer0.org1.example.com
  template:
    metadata:
      labels:
        app: peer0.org1.example.com
    spec:
      containers:
      - name: peer0.org1.example.com
        # Image used
        image: salmandabbakuti/basic-network-k8s-peer:1.1
        # Uncomment the following during development/testing of the image
        # imagePullPolicy: Always
        env:
          - name: FABRIC_CFG_PATH
            value: /var/hyperledger/config
          - name: FABRIC_LOGGING_SPEC
            value: DEBUG
          - name: ORDERER_ADDRESS
            value: orderer.example.com-clusterip:30750
          - name: ORG_CONTEXT
            value: org1.example
          - name: CORE_PEER_ADDRESS
            value: peer0.org1.example.com-clusterip:30751
            # value: localhost:30751
        volumeMounts:
        - name: peer0.org1.example.com-ledger
          mountPath: /var/ledger
        - name: dockersock
          mountPath: /var/run/docker.sock
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
  volumeClaimTemplates:
  - metadata: 
      name: peer0.org1.example.com
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: general
      resources:
        requests:
          storage: 1Gi

---
# Expose the port 7051 as ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: peer0.org1.example.com-clusterip

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: peer0.org1.example.com

  ports:
    - name: peer0.org1.example.com-clusterip
      port: 30751
    - name: peer0.org1.example.com-cc-clusterip
      port: 30752

  type: ClusterIP

---
# Expose the port 30751 as node port -  NEEDED if you
# are interested in connecting to the Pods from the Host
# machine - keep in mind you would need the IP for the node
# port service
apiVersion: v1
kind: Service
metadata:
  name: peer0.org1.example.com-nodeport

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: peer0.org1.example.com

  ports:
    - name: peer0.org1.example.com-nodeport-751
      port: 30751
      nodePort: 30751
    - name: peer0.org1.example.com-cc-nodeport-752
      port: 30752
      nodePort: 30752

  type: NodePort
